Made random data generation generic.
lemire/FastPFor pull request #102
Opened 2023-02-16 20:22 UTC by cbsmith

Per [discussion](https://github.com/lemire/FastPFor/pull/101#discussion_r1108965556), making this a separate pull request.

2023-02-16 20:42 UTC, lemire commented
@cbsmith Thanks.

2023-02-16 20:48 UTC, cbsmith commented
Hrm... not sure why the build failures are occurring. I'll take a look at this later tonight.

2023-02-19 20:53 UTC, pps83 commented on unittest/test_fastpfor.cpp
>            std::mt19937_64 e2(123456);
Not related to the PR, but the test might have discovered some hidden issues if it didn't use fixed seed. Perhaps, using device_random or time to seed generator and then, saving the seed is a better approach: If a test fails, then it should report the seed to be able to repro the test case.

2023-02-19 21:02 UTC, cbsmith commented on unittest/test_fastpfor.cpp
>            std::mt19937_64 e2(123456);
That seems like a good suggestion.

2023-02-19 21:12 UTC, pps83 requested changes

2023-02-19 21:12 UTC, pps83 commented on unittest/test_fastpfor.cpp
>            v.clear();
```suggestion
        void _genDataRandom(std::vector<T>& v, size_t values) {
          v.resize(values);
```

2023-02-19 21:13 UTC, pps83 commented on unittest/test_fastpfor.cpp
>            v.clear();
this should fix the crash

2023-02-19 21:36 UTC, cbsmith commented on unittest/test_fastpfor.cpp
>            v.clear();
Yeah, I realized this just now as I got a chance to look at this again. I'm kind of surprised the tests passed on my own machine though. A little freaky.

2023-02-20 00:58 UTC, lemire commented on unittest/test_fastpfor.cpp
>            std::mt19937_64 e2(123456);
I agree that it is most helpful to use fixed seeds.

2023-02-20 02:31 UTC, cbsmith commented
Fixed the vector sizing error. Tests should pass now.

2023-02-20 15:43 UTC, lemire commented
Running tests now.

2023-02-20 15:51 UTC, lemire commented
Merging.

2023-02-20 15:51 UTC, merged